  FROM python:3.11
  
  WORKDIR /app
  
  COPY IsolationForestService.py .
  
  RUN pip install \
      flask \
      scikit-learn \
      numpy \
      requests
  
  EXPOSE 5000
  
  CMD ["python", "IsolationForestService.py"]